version: '3'

services:
  server:
    build: ./server
    volumes:
      - ./server:/server/app/
    env_file: .env-server
    stdin_open: true # docker run -i
    tty: true # docker run -t
    ports:
      - 80:3000
